language: node_js
node_js:
- '0.10'
notifications:
  slack:
    secure: LyCP//iisSxh/3v9urN/DIzC80LMekzYEe86mIhlq7tV0FChayGHf0skdZSA5o4FqQaR9NpQQ/aWjSJS5vAkZYbOeYIlrD9KrnljYAUAYEsh35RCu813NHv3hQCS3BGFdYiH5bc804ZN5zsUJ7FlsXrpKhrpxpyGdIFJZEbCpFdqoxPjq0jBTZdlXMuHty1a8sYFjB8kbxkyWcBuPYJjmk4JOYfiOys0oJO+MfD9uj5j7+XpyS79nfiLHEpRzwhjKmpSVIk+mKy1R5WY49klz8De2pTzlwN0kH6lvn03wOvT+GUnd5vSOqgTqzAbztZUYK/Ee6oUnnQxqE57xBq8RzhJHAr3h+bqFbxdnPjA1ZknJKy3XCcD0RSG2dYC+fLC6rReNI8TIvwBoxidIMSRPr8acIGRoVuo7laTWXAz3zonPVnS8TiiyHGe2jyHHyvTMgB4vTPYgD91ODEjgiPBRd0oV4aSoFjiKGuFIn6AD1hB+00fUYBFR9dL87VCGR5l9j7Hz3C/chkozwo4pSebpVawCewgskuDY3u3aaDrHBkoNcgdCndOj3I0m50SFhHb7kWuQyLd+myxmgoRtOIjgPMIikMWm75h2Esj0TYd8Rj43tIozQtdKFMKz+TjAOu3/OKHCaa9pbpZmmOHEFZ5WT3YQf8RjjTk0TjPRkiuKlA=
